### PR TITLE
Add nashorn runtime

### PR DESCRIPTION
**Pull request by Connorhd**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This PR needs a rebase

**Comment by Connorhd** [comment]
If I rebase it will it get merged? (this had been open for nearly a year on the previous repo)

**Comment by rafaelfranca** [comment]
I don't see any reason to not merge it. cc @josh

**Comment by josh** [comment]
This needs to be configured to actually run in CI. Right now its not tested.

**Comment by Connorhd** [comment]
I'm not sure what you mean, you can see the test results here https://travis-ci.org/Connorhd/execjs/jobs/25844982

**Comment by josh** [comment]
That test run is from a year ago.

**Comment by Connorhd** [comment]
The code is from a year ago, I can rebase and re-run tests, I just didn't want to waste my time if this PR is going to be left open for another year.

**Comment by josh** [comment]
I think its best to just close this then. We're probably not going to put much effort into debugging issues around nashorn.

**Comment by Connorhd** [comment]
Wow, seems like a pretty unfortunate attitude to take. It's not like this project is particularly fast moving or nashorn is going to be an unstable runtime. Adding it gives anyone running jruby on java 8 a runtime with no dependencies which seems like a win.

**Pull request closed without merging**
